from models.database import db

# from models.accounts_module.user import ...
# from models.accounts_module.channel import ...

# from models.content_module.category import ...
# from models.content_module.video import ...

# from models.interaction_module.comment import ...
# from models.interaction_module.like import ...
# from models.interaction_module.playlist import ...

def create_tables(): #database deki tabloları oluşturmayı sağlayan fonksiyon
    with db:
        pass

    print("Veritabanı tabloları güncellendi")
